name:                time-keeper
version:             0.1.0.0
github:              "githubuser/time-keeper"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/time-keeper#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- yaml
- time >= 1.9.1
- filepath
- classy-prelude
- prettyprinter
- containers
- mono-traversable
- optparse-applicative

executables:
  time-keeper:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
